version: '3'
services:
  pastebin-mirror:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - "${PASTEBIN_MIRROR_DIR}:/pastebin-mirror"
    restart: unless-stopped